
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/game/game.js",
	"libs/modules/game/game.native.js",
	"libs/modules/tween/tween.js",
	"libs/modules/md5/md5.js",
	"libs/modules/uploadLib/uploadLib.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/controller/ControllerManager.js",
	"bin-debug/controller/gameUI/AggregationController.js",
	"bin-debug/controller/gameUI/BuyTicketController.js",
	"bin-debug/controller/gameUI/FansRecruitController.js",
	"bin-debug/controller/gameUI/GameMainController.js",
	"bin-debug/controller/gameUI/GarbageCollectionController.js",
	"bin-debug/controller/gameUI/GroupManagementAuditController.js",
	"bin-debug/controller/gameUI/GroupManagerController.js",
	"bin-debug/controller/gameUI/HeadLineController.js",
	"bin-debug/controller/gameUI/HeadLineItemInfoController.js",
	"bin-debug/controller/gameUI/MonthTieController.js",
	"bin-debug/controller/gameUI/NewStarController.js",
	"bin-debug/controller/gameUI/PayController.js",
	"bin-debug/controller/gameUI/RankGroupContributionController.js",
	"bin-debug/controller/gameUI/RankGroupController.js",
	"bin-debug/controller/gameUI/RankStarController.js",
	"bin-debug/controller/gameUI/RankUserContributionController.js",
	"bin-debug/controller/gameUI/signInController.js",
	"bin-debug/controller/gameUI/StarFansTVController.js",
	"bin-debug/controller/gameUI/SweepsTasksController.js",
	"bin-debug/controller/gameUI/TaskController.js",
	"bin-debug/controller/gameUI/TopRankGroupController.js",
	"bin-debug/controller/gameUI/UploadController.js",
	"bin-debug/controller/gameUI/WeekPushController.js",
	"bin-debug/controller/loader/LoaderManager.js",
	"bin-debug/controller/loader/LoadStar.js",
	"bin-debug/controller/util/BaseURLLoader.js",
	"bin-debug/controller/Util.js",
	"bin-debug/data/DataManager.js",
	"bin-debug/data/PomeloData.js",
	"bin-debug/data/Sounds.js",
	"bin-debug/data/Tools.js",
	"bin-debug/data/UpLoadFile.js",
	"bin-debug/GameApp.js",
	"bin-debug/IoConnect.js",
	"bin-debug/JsonpReq.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/Manager.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/view/common/BaseView.js",
	"bin-debug/view/gameUI/aler/AlertManager.js",
	"bin-debug/view/gameUI/aler/AlertPanel.js",
	"bin-debug/view/gameUI/aler/AlertPanel1.js",
	"bin-debug/view/gameUI/barrage/BarrageItem.js",
	"bin-debug/view/gameUI/barrage/BarrageMananger.js",
	"bin-debug/view/gameUI/buyTicketActive/AlertBuyTicket.js",
	"bin-debug/view/gameUI/buyTicketActive/AlertContent.js",
	"bin-debug/view/gameUI/buyTicketActive/AwardPerson.js",
	"bin-debug/view/gameUI/buyTicketActive/BuyTicket.js",
	"bin-debug/view/gameUI/buyTicketActive/BuyTicketManager.js",
	"bin-debug/view/gameUI/buyTicketActive/CommentStyle.js",
	"bin-debug/view/gameUI/containmoney/ContainMoneyItem.js",
	"bin-debug/view/gameUI/containmoney/ContainmoneyOpen.js",
	"bin-debug/view/gameUI/containmoney/ContainmoneyUI.js",
	"bin-debug/view/gameUI/fansRecruit/FansRecruitItem.js",
	"bin-debug/view/gameUI/fansRecruit/FansRecruitManager.js",
	"bin-debug/view/gameUI/fansRecruit/FansRecruitUI.js",
	"bin-debug/view/gameUI/flower/FlowerBtnSend.js",
	"bin-debug/view/gameUI/flower/FlowerItem.js",
	"bin-debug/view/gameUI/flower/FlowerUI.js",
	"bin-debug/view/gameUI/follow/Follow.js",
	"bin-debug/view/gameUI/garbageCollection/GarbageCollection.js",
	"bin-debug/view/gameUI/garbageCollection/GarbageCollectionManager.js",
	"bin-debug/view/gameUI/garbageCollection/WorksItem.js",
	"bin-debug/view/gameUI/headlines/HeadLineItemInfoManager.js",
	"bin-debug/view/gameUI/headlines/HeadLineItemInfor.js",
	"bin-debug/view/gameUI/headlines/HeadLines.js",
	"bin-debug/view/gameUI/headlines/HeadLinesItem.js",
	"bin-debug/view/gameUI/headlines/HeadlinesManager.js",
	"bin-debug/view/gameUI/headlines/HeadLinesStarImg.js",
	"bin-debug/view/gameUI/headlines/mySelfStar/MyselfHeadLines.js",
	"bin-debug/view/gameUI/headlines/mySelfStar/MySelfHeadLinesItem.js",
	"bin-debug/view/gameUI/headlines/mySelfStar/StarIcon.js",
	"bin-debug/view/gameUI/liveChatRoom/LiveChatRoomManager.js",
	"bin-debug/view/gameUI/liveChatRoom/LiveChatRoomUI.js",
	"bin-debug/view/gameUI/liveChatRoom/LiveTalkChat.js",
	"bin-debug/view/gameUI/liveChatRoom/LiveTalkChatItem.js",
	"bin-debug/view/gameUI/mainUI/BtnBuluo.js",
	"bin-debug/view/gameUI/mainUI/BtnMain.js",
	"bin-debug/view/gameUI/mainUI/GameMainManager.js",
	"bin-debug/view/gameUI/mainUI/GameMainUI.js",
	"bin-debug/view/gameUI/mainUI/HumenBody.js",
	"bin-debug/view/gameUI/mainUI/HumenUI.js",
	"bin-debug/view/gameUI/mainUI/MainProIcon.js",
	"bin-debug/view/gameUI/mainUI/MainUI.js",
	"bin-debug/view/gameUI/mainUI/MainZcItem.js",
	"bin-debug/view/gameUI/mainUI/StarTx.js",
	"bin-debug/view/gameUI/mbarrage/MBarrageItem.js",
	"bin-debug/view/gameUI/mbarrage/MBarrageUI.js",
	"bin-debug/view/gameUI/module/BaseCircleImage.js",
	"bin-debug/view/gameUI/module/BaseEuiImage.js",
	"bin-debug/view/gameUI/monthTie/MonthTie.js",
	"bin-debug/view/gameUI/monthTie/MonthTieManager.js",
	"bin-debug/view/gameUI/monthTie/MonthTieMonth.js",
	"bin-debug/view/gameUI/monthTie/MonthTie_FansTable_Item.js",
	"bin-debug/view/gameUI/monthTie/MonthTie_HeatTable_Item.js",
	"bin-debug/view/gameUI/monthTie/MonthTie_StarTable_Item.js",
	"bin-debug/view/gameUI/newstar/NewStarCheckBoxItem.js",
	"bin-debug/view/gameUI/newstar/NewStarManager.js",
	"bin-debug/view/gameUI/newstar/NewStarSerachUI.js",
	"bin-debug/view/gameUI/newstar/NewStarUI.js",
	"bin-debug/view/gameUI/pay/PayManager.js",
	"bin-debug/view/gameUI/pay/PayUI.js",
	"bin-debug/view/gameUI/rankGroup/GroupBookUI.js",
	"bin-debug/view/gameUI/rankGroup/RankGroupItem.js",
	"bin-debug/view/gameUI/rankGroup/RankGroupItem1.js",
	"bin-debug/view/gameUI/rankGroup/RankGroupItem2.js",
	"bin-debug/view/gameUI/rankGroup/RankGroupManager.js",
	"bin-debug/view/gameUI/rankGroup/RankGroupUI.js",
	"bin-debug/view/gameUI/rankGroupContribution/groupXuan/GroupXuan.js",
	"bin-debug/view/gameUI/rankGroupContribution/RankGroupContributionManager.js",
	"bin-debug/view/gameUI/rankGroupContribution/RankGroupContributionUI.js",
	"bin-debug/view/gameUI/rankGroupContribution/RankGroupItem.js",
	"bin-debug/view/gameUI/rankGroupContribution/RankGroupItem1.js",
	"bin-debug/view/gameUI/rankStar/RankStarItem.js",
	"bin-debug/view/gameUI/rankStar/RankStarManager.js",
	"bin-debug/view/gameUI/rankStar/RankStarUI.js",
	"bin-debug/view/gameUI/rankUserContribution/RankUserContributionItem.js",
	"bin-debug/view/gameUI/rankUserContribution/RankUserContributionItem1.js",
	"bin-debug/view/gameUI/rankUserContribution/RankUserContributionManager.js",
	"bin-debug/view/gameUI/rankUserContribution/RankUserContributionUI.js",
	"bin-debug/view/gameUI/starfanstv/StarFansTVManager.js",
	"bin-debug/view/gameUI/starfanstv/StarFansTVUI.js",
	"bin-debug/view/gameUI/starfanstv/StarFanTVItem.js",
	"bin-debug/view/gameUI/starPage/StarPageItem.js",
	"bin-debug/view/gameUI/starPage/StarPageManager.js",
	"bin-debug/view/gameUI/starPage/StarPageTip.js",
	"bin-debug/view/gameUI/starPage/StarPageUI.js",
	"bin-debug/view/gameUI/sweepsTasks/SweepsTasks.js",
	"bin-debug/view/gameUI/sweepsTasks/SweepsTasksManager.js",
	"bin-debug/view/gameUI/system/GroupJoin.js",
	"bin-debug/view/gameUI/system/GroupReward.js",
	"bin-debug/view/gameUI/system/Image.js",
	"bin-debug/view/gameUI/system/notice/Notice.js",
	"bin-debug/view/gameUI/system/Publish/NewPublish.js",
	"bin-debug/view/gameUI/system/Publish/Part1.js",
	"bin-debug/view/gameUI/system/Share.js",
	"bin-debug/view/gameUI/system/TipText.js",
	"bin-debug/view/gameUI/system/TipText1.js",
	"bin-debug/view/gameUI/system/TopScreenOfGroupRank/TopGroupRank.js",
	"bin-debug/view/gameUI/system/TopScreenOfGroupRank/TopGroupRankManager.js",
	"bin-debug/view/gameUI/system/TopScreenOfGroupRank/TopRank.js",
	"bin-debug/view/gameUI/task/aggregation/AggregationIcon.js",
	"bin-debug/view/gameUI/task/aggregation/AggregationIcon1.js",
	"bin-debug/view/gameUI/task/aggregation/AggregationIconUp.js",
	"bin-debug/view/gameUI/task/aggregation/AggregationManager.js",
	"bin-debug/view/gameUI/task/giftcf/GiftCf.js",
	"bin-debug/view/gameUI/task/giftcf/GiftCfBtn.js",
	"bin-debug/view/gameUI/task/giftcf/GiftCfItem.js",
	"bin-debug/view/gameUI/task/giftcf/GiftCfItem1.js",
	"bin-debug/view/gameUI/task/giftcf/GiftManager.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagement.js",
	"bin-debug/view/gameUI/task/groupManagement/groupManagementAudit.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementAuditItem.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementAuditItemInformation.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementAuditItemInformationItem.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementAuditManager.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementItem.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementItemInformation.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagementPush.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManager.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagerPushImage.js",
	"bin-debug/view/gameUI/task/groupManagement/GroupManagerPushImage1.js",
	"bin-debug/view/gameUI/task/groupManagement/HostManagement.js",
	"bin-debug/view/gameUI/task/groupXuan/TaskGroupXuan.js",
	"bin-debug/view/gameUI/task/signIn/SignIn.js",
	"bin-debug/view/gameUI/task/signIn/SignInManager.js",
	"bin-debug/view/gameUI/task/signIn/SignPersonIcon.js",
	"bin-debug/view/gameUI/task/TaskHallofFame.js",
	"bin-debug/view/gameUI/task/TaskIcon.js",
	"bin-debug/view/gameUI/task/TaskItem.js",
	"bin-debug/view/gameUI/task/TaskManager.js",
	"bin-debug/view/gameUI/task/taskoepn/TaskOpenManager.js",
	"bin-debug/view/gameUI/task/taskoepn/TaskOpenUI.js",
	"bin-debug/view/gameUI/task/TaskOpen.js",
	"bin-debug/view/gameUI/task/TaskTip.js",
	"bin-debug/view/gameUI/task/TaskUI.js",
	"bin-debug/view/gameUI/upload/Upload.js",
	"bin-debug/view/gameUI/upload/UploadDesc.js",
	"bin-debug/view/gameUI/upload/UploadItem.js",
	"bin-debug/view/gameUI/upload/UploadManager.js",
	"bin-debug/view/gameUI/userPanel/UserPaise.js",
	"bin-debug/view/gameUI/userPanel/UserPaiseIcon.js",
	"bin-debug/view/gameUI/userPanel/UserPanel.js",
	"bin-debug/view/gameUI/userPanel/UserPanelItem.js",
	"bin-debug/view/gameUI/weekPush/newWeekPush/NewWeekPush.js",
	"bin-debug/view/gameUI/weekPush/newWeekPush/NewWeekPushContributionItem.js",
	"bin-debug/view/gameUI/weekPush/newWeekPush/NewWeekPushHonor.js",
	"bin-debug/view/gameUI/weekPush/WeekPushManage.js",
	"bin-debug/view/gameUI/zfdy/Collection.js",
	"bin-debug/view/gameUI/zfdy/zfBag/Zfdy10.js",
	"bin-debug/view/gameUI/zfdy/zfBag/Zfdy11.js",
	"bin-debug/view/gameUI/zfdy/zfBag/Zfdy12.js",
	"bin-debug/view/gameUI/zfdy/Zfdy1.js",
	"bin-debug/view/gameUI/zfdy/Zfdy2.js",
	"bin-debug/view/gameUI/zfdy/Zfdy3.js",
	"bin-debug/view/gameUI/zfdy/Zfdy4.js",
	"bin-debug/view/gameUI/zfdy/Zfdy5.js",
	"bin-debug/view/gameUI/zfdy/Zfdy6.js",
	"bin-debug/view/gameUI/zfdy/Zfdy7.js",
	"bin-debug/view/gameUI/zfdy/Zfdy8.js",
	"bin-debug/view/gameUI/zfdy/Zfdy9.js",
	"bin-debug/view/gameUI/zfdy/ZfdyHeadItem.js",
	"bin-debug/view/gameUI/zfdy/ZfHeadItem.js",
	"bin-debug/view/loader/Loading.js",
	"bin-debug/view/loader/MainLoading.js",
	"bin-debug/view/loader/ModuleLoading.js",
	"bin-debug/view/ViewManager.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "GameApp",
		frameRate: 60,
		scaleMode: "fixedWidth",
		contentWidth: 750,
		contentHeight: 1206,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:30,textColor:0x00c200,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};